name: "lint"

on:
  push:
    branches: [ "**" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
          
      - name: GolangCI-Linter
        uses: Mushus/golangci-linter@v1.1.2
        with:
          basePath: .
